### ISSUE TITLE
API: Get an account by username

### ISSUE THREAD

**Issue by mrpudn** [mrpudn/wtf#16]
Request:
```
GET /api/accounts?username=foobar
```
Response:
```
{
  "uuid": "3dc8f639-c8b4-4cc8-bdee-cc024d2ce4e8",
  "email": "foobar@gmail.com",
  "password": "foobar123",
  "username": "foobar"
}
```

Requires #12.

**Comment by njgrisafi** [comment]
Going to start this issue this week. Looking forward to contributing!

**Comment by mrpudn** [comment]
Awesome - I'll try to get some of the other stuff added hopefully today and tomorrow so you can reference it.

Today, I've just been doing some refactoring here and there, but I think I'm close to implementing some of the REST endpoints ;)

Will keep you posted.

**Comment by njgrisafi** [comment]
Awesome sounds good! I liked your approach with the functional programming with JavaScript and definitely want to keep learning!

Let me know when you get that branch up. In the mean time, I'll look around the repo and get familiar with the project setup.

I'm also going to provision a Ubuntu VM image for development (Windows causing too many struggles)

**Comment by mrpudn** [comment]
Good idea - are you using [Vagrant](https://github.com/hashicorp/vagrant)? Might make it easier to manage your dev VM(s), and I'm sure you can find a good pre-built Vagrant box out there. I was working on some PHP stuff a while back and the [Homestead](https://github.com/laravel/homestead) box worked wonders.

Sorry, I owe you a branch haha - let me finish up the `POST /accounts` endpoint that I've been working on tonight and create a branch for this

**Comment by njgrisafi** [comment]
Awesome - I've never used Vagrant before but I went a head with the installation I used [dev_base](https://app.vagrantup.com/brd/boxes/dev_base) box for **wtf** and got it up and running in no time!

Just had to install pip and map the guest port 5000 to the host port 5000 in the **Vagrantfile**. Maybe we can create our own [Vagrant box](https://www.vagrantup.com/docs/boxes/base.html).

Thanks for the suggestion!

**Comment by mrpudn** [comment]
Yup, I was thinking about having a `Vagrantfile` in the root of the directory in case people wanted to develop within Vagrant. I'll create an issue for that and assign you if you're up for it ;)

**Comment by mrpudn** [comment]
I'm closing this issue, as we're removing the `username` field from accounts. We might add this later.
