### ISSUE TITLE
Migrate tests alongside code

### ISSUE THREAD

**Issue by njgrisafi** [mrpudn/wtf#29]
To maintain simplicity tests should be migrated to be [alongside the application code ](https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code)
```
setup.py
mypkg/
    __init__.py
    app.py
    view.py
    test_app.py
    test_view.py
    /foo
        __init__.py
        bar.py
        baz.py
        test_bar.py
        test_baz.py
```
**imports** will also be condensed

Instead of this:
```python
import foo.bar.baz.where.are.you
```
You can do this:
```python
import .you
````

Based on the discussion #27

**Comment by njgrisafi** [comment]
@mrpudn not sure how to add this to the backlog on the Kanban Board

**Comment by mrpudn** [comment]
Oops just had a second look at this - this is what I was thinking actually:
```
setup.py
mypkg/
    __init__.py
    app.py
    view.py
    test_app.py
    test_view.py
    /foo
        __init__.py
        bar.py
        baz.py
        test_bar.py
        test_baz.py
```

**Comment by mrpudn** [comment]
> @mrpudn not sure how to add this to the backlog on the Kanban Board

You have to click the `+ Add Cards` link

**Comment by njgrisafi** [comment]
@mrpudn updated the issue description and added it to the backlog
